name: "Setup Devenv"
description: "Prepares image with packages and cleanup"
runs:
  using: "composite"
  steps:
    - name: Show CPU Model and Free Space
      shell: bash
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cat /proc/cpuinfo | grep 'model name'
        free -h
    
    - name: check disk space
      shell: bash
      run: |
        df -h
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      shell: bash
      run: |
        sudo -E apt-get update -y
        #24.04sudo -E apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
        sudo -E apt-get install -y build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python3 unzip wget
        sudo -E apt-get install -y python3-pyelftools
        sudo -E apt-get install -y python3-distutils python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev 

        #sudo -E apt-get install -y rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python3 python3-pip python3-ply haveged lrzsz device-tree-compiler scons
        sudo -E apt-get install clang llvm
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        df -h
